const GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta";

function getKey() {
  return (
    process.env.GEMINI_API_KEY ||
    process.env.GOOGLE_GENERATIVE_API_KEY ||
    ""
  ).replace(/"/g, "");
}

function getModel() {
  return process.env.AI_MODEL || "gemini-flash-latest";
}

function isMockForced() {
  return process.env.AI_MOCK === "1" || !getKey();
}

function mockDraft(prompt) {
  return [
    "Exciting news from Divinenet!",
    "",
    "We are thrilled to share a fresh update for our clients and followers. This fictional campaign post was generated by the Divinenet AI assistant to demonstrate the draft workflow.",
    "",
    "Tap the link to learn more and join the conversation.",
    "",
    "#Divinenet #Marketing"
  ].join("\n");
}

async function callGemini(prompt) {
  const response = await fetch(
    `${GEMINI_API_BASE}/models/${getModel()}:generateContent?key=${encodeURIComponent(getKey())}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ role: "user", parts: [{ text: prompt }] }]
      })
    }
  );

  if (!response.ok) {
    throw new Error(`Gemini API error: HTTP ${response.status}`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts
    ?.map((part) => part.text || "")
    .join("\n")
    .trim();

  if (!text) {
    throw new Error("Gemini returned an empty draft");
  }

  return text;
}

async function generateDraft(prompt) {
  if (isMockForced()) {
    return { draft: mockDraft(prompt), provider: "mock", model: "offline" };
  }

  try {
    const draft = await callGemini(prompt);
    return { draft, provider: "gemini", model: getModel() };
  } catch (error) {
    return {
      draft: mockDraft(prompt),
      provider: "mock",
      model: "fallback",
      warning: error.message
    };
  }
}

module.exports = {
  generateDraft,
  getModel,
  getKey
};